ignore:
  - "**/example/sampletestingproject/config/**"
  - "**/example/sampletestingproject/gateway/http/mapping/**"
  - "**/example/sampletestingproject/SampleTestingProjectApplication.java"
  - "**/example/sampletestingproject/domain/**"
  - "**/example/sampletestingproject/gateway/http/json/**"